services:
  mysql8:
    image: mysql:8.0
    restart: always
    command:
      - --default_authentication_plugin=mysql_native_password
      - --binlog-format=ROW
      - --server-id=1
      - --innodb_log_file_size=2M
      - --innodb_buffer_pool_size=64M
      - --innodb_log_buffer_size=1M
    environment:
      MYSQL_ROOT_PASSWORD: root
#    volumes:
#      - ./script/mysql/:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"